import {
  AirVent,
  ArrowUpDown,
  Bath,
  BedDouble,
  Building2,
  CalendarX,
  CookingPot,
  DoorOpen,
  Footprints,
  Layers,
  Microwave,
  Refrigerator,
  Ruler,
  ShowerHead,
  Sofa,
  Toilet,
  Utensils,
  WashingMachine,
  Wifi,
  CircleHelp,
  Users,
  Star,
  Clock,
  Receipt,
  type LucideIcon,
} from "lucide-react";
const icons: Record<string, LucideIcon> = {
  properBeds: BedDouble,
  bedrooms: DoorOpen,
  areaM2: Ruler,
  toilets: Toilet,
  showers: ShowerHead,
  showerLayout: Bath,
  lift: ArrowUpDown,
  floor: Building2,
  entranceSteps: Footprints,
  internalStairs: Layers,
  accessSuitable: Footprints,
  diningSeats: Utensils,
  kitchen: CookingPot,
  kitchenQuality: CookingPot,
  diningQuality: Utensils,
  dishwasher: Utensils,
  oven: Microwave,
  hob: CookingPot,
  fridge: Refrigerator,
  washingMachine: WashingMachine,
  airConditioning: AirVent,
  wifi: Wifi,
  cancellation: CalendarX,
  bathrooms: Bath,
  capacity: Users,
  rating: Star,
  walk: Clock,
  price: Receipt,
  bedLayout: Sofa,
};
export function FactIcon({ name, size = 17 }: { name: string; size?: number }) {
  const Icon = icons[name] ?? CircleHelp;
  return <Icon size={size} aria-hidden="true" strokeWidth={1.8} />;
}
